export const Chats = [
    {
        link: "/formatos-ejemplo-para-borrar",
        title: "Formatos para borrar",
        message: "Esto es para guiarse, al final se borra",
        time: "18:16",
        avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUJHEpo9ACG4d7XCFxS3pRgteZg4gb64dKIg&s",
        isPinned: true,
        isMute: false,
        isRead: false,
    },
    {
        link: "/",
        title: "CiberAlerta Perú",
        message: "Bienvenidos al especial",
        time: "Jueves",
        avatar: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        isPinned: false,
        isMute: false,
        isRead: true,
    },
    {
        link: "/que-es-la-ciberdelincuencia",
        title: "¿Qué es la ciberdelincuencia?",
        message: "¿Cómo ha ido creciendo este delito?",
        time: "18:10",
        avatar: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        isPinned: true,
        isMute: true,
        isRead: false,
    },
    {
        link: "/ciberdelincuencia-en-nuestro-pais",
        title: "Ciberdelincuencia en nuestro país",
        message: "Ciberdelincuencia en el Perú",
        time: "18:16",
        avatar: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        isPinned: true,
        isMute: false,
        isRead: false,
    },
    {
        link: "/formas-comunes-de-ataques-ciberdigitales",
        title: "Formas comúnes de ataques ciberdigitales",
        message: "Texto",
        time: "18:16",
        avatar: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        isPinned: true,
        isMute: false,
        isRead: false,
    },
    {
        link: "/estado-de-denuncias-por-ciberdelitos",
        title: "Estado de denuncias por ciberdelitos",
        message: "Texto",
        time: "18:16",
        avatar: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        isPinned: true,
        isMute: false,
        isRead: false,
    },
    {
        link: "/victimas",
        title: "Víctimas",
        message: "Texto",
        time: "18:16",
        avatar: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        isPinned: true,
        isMute: false,
        isRead: false,
    },
    {
        link: "/especialistas",
        title: "Especialistas",
        message: "Texto",
        time: "18:16",
        avatar: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        isPinned: true,
        isMute: false,
        isRead: false,
    },
    {
        link: "/verificador-de-links",
        title: "Verificador de Links Livia",
        message: "Verify your links now",
        time: "Yesterday",
        avatar: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        isPinned: false,
        isMute: true,
        isRead: false,
    },
    {
        link: "/creditos",
        title: "Créditos",
        message: "Texto",
        time: "18:16",
        avatar: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        isPinned: true,
        isMute: false,
        isRead: false,
    },
    {
        link: "/otros",
        title: "Otros",
        message: "Texto",
        time: "18:16",
        avatar: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        isPinned: true,
        isMute: false,
        isRead: false,
    },
];