export const Chats = [
    // {
    //     id: '',
    //     link: "/formatos-ejemplo-para-borrar",
    //     title: "Formatos para borrar",
    //     message: "Esto es para guiarse, al final se borra",
    //     time: "18:16",
    //     avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUJHEpo9ACG4d7XCFxS3pRgteZg4gb64dKIg&s",
    //     isPinned: true,
    //     isMute: false,
    //     isRead: false,
    // },
    // {
    //     id: '',
    //     link: "/ejemplo-chat",
    //     title: "Ejemplo Chat",
    //     message: "Esto es para guiarse, al final se borra",
    //     time: "18:16",
    //     avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUJHEpo9ACG4d7XCFxS3pRgteZg4gb64dKIg&s",
    //     isPinned: true,
    //     isMute: false,
    //     isRead: false,
    // },
    {
        id: 'inicio',
        link: "/",
        title: "CiberAlerta Perú",
        subtitle: "Bienvenidos...",
        message: "Bienvenidos al nuevo especial",
        time: "Jueves",
        avatar: "chat-icons/1.webp",
        isPinned: true,
        isMute: false,
        isRead: true,
    },
    {
        id: 'ciberalerta-peru',
        link: "/ciberdelincuencia",
        title: "Ciberdelincuencia",
        subtitle: "Ciberdelincuencia",
        message: "¿Qué es la ciberdelincuencia?",
        time: "18:18",
        avatar: "chat-icons/2.webp",
        isPinned: false,
        isMute: false,
        isRead: false,
    },
    {
        id: 'un-poco-de-data',
        link: "/un-poco-de-data",
        title: "Un poco de data",
        subtitle: "Un poco de data",
        message: "La ciberdelincuencia en cifras",
        time: "18:16",
        avatar: "chat-icons/3.webp",
        isPinned: false,
        isMute: false,
        isRead: false,
    },
    {
        id: 'el-phishing',
        link: "/el-phishing",
        title: "El “Phishing”",
        subtitle: "El “Phishing”",
        message: "Uno de los ciberdelitos con mayor crecimiento ",
        time: "18:10",
        avatar: "chat-icons/4.webp",
        isPinned: false,
        isMute: false,
        isRead: false,
    },
    {
        id: 'testimonios',
        link: "/testimonios",
        title: "Testimonios",
        subtitle: "Testimonios",
        message: "Algunas víctimas de ciberdelitos y sus historias",
        time: "17:38",
        avatar: "chat-icons/5.webp",
        isPinned: false,
        isMute: false,
        isRead: false,
    },
    {
        id: 'opiniones-sobre-la-ciberdelincuencia',
        link: "/opiniones-sobre-la-ciberdelincuencia",
        title: "Opiniones sobre la ciberdelincuencia",
        subtitle: "Especialistas",
        message: "¿Qué dicen los especialistas?",
        time: "17:35",
        avatar: "chat-icons/6.webp",
        isPinned: false,
        isMute: false,
        isRead: false,
    },
    {
        id: 'prevencion-y-denuncia',
        link: "/prevencion-y-denuncia",
        title: "Prevención y denuncia",
        subtitle: "Prevención y denuncia",
        message: "¿Cómo prevenir estos ciberdelitos?",
        time: "17:26",
        avatar: "chat-icons/7.webp",
        isPinned: false,
        isMute: false,
        isRead: false,
    },
    {
        id: 'verificador-de-links',
        link: "/verificador-de-links",
        title: "Verificador de enlaces",
        subtitle: "Verificador de enlaces",
        message: "¡Descubre a la nueva verificadora de enlaces!",
        time: "16:11",
        avatar: "chat-icons/8.webp",
        isPinned: false,
        isMute: false,
        isRead: false,
    },
    {
        link: "/creditos",
        title: "Créditos",
        subtitle: "Créditos",
        message: "Este especial fue hecho por...",
        time: "00:08",
        avatar: "chat-icons/9.webp",
        isPinned: false,
        isMute: false,
        isRead: false,
    },
];