export const Participants = [
    {
        id: 1,
        name: "Sebastian Fernandez - Moris",
        subtitle: "Coordinador de Proyectos",
        avatar: "https://media.licdn.com/dms/image/v2/D4E03AQFUEOhuM8r6vA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1700267567541?e=1740009600&v=beta&t=bN-bkU-p_OagsSMqq9Zz-cfKB8WbJcHn_8f6zNkBZxo",
    },
    {
        id: 2,
        name: "Daniel Zapata",
        subtitle: "Coordinador de Desarrollo",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/Fotos%20Lab%20Brenda/Daniel.jpg",
    },
    {
        id: 3,
        name: "Diego Aquino",
        subtitle: "Asistente de Coordinación",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/Diego%20Aquino.jpeg",
    },
    {
        id: 4,
        name: "Gustavo Huamani",
        subtitle: "Coordinador de Diseño",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/Gustavo%20Huamani%20Pimentel.jpg",
    },
    {
        id: 5,
        name: "Verenizze Lara",
        subtitle: "Coordinadora de Periodismo y Datos",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/Vere.png",
    },
    {
        id: 6,
        name: "María Belén Pérez Bless",
        subtitle: "Editora Periodística y Traductora",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/Mabe.png",
    },
    {
        id: 7,
        name: "Rosario Arribasplata",
        subtitle: "Diseño",
        avatar: "https://media.licdn.com/dms/image/v2/D4E03AQGxdI5GZm0qbA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1728940020012?e=1740009600&v=beta&t=Mghn7YTp-yQnOjjWjhD04cHt_BM1-binyJNT40JieNI",
    },
    {
        id: 8,
        name: "Ximena Maticorena",
        subtitle: "Audiovisuales",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/Ximena%20Maticorena.png",
    },
    {
        id: 9,
        name: "Danny Dávila",
        subtitle: "Audiovisuales",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/Danny Dávila.jpg",
    },
    {
        id: 10,
        name: "Antuanet Cordova",
        subtitle: "Audiovisuales",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/Antuanet Cordova Reategui.jpeg",
    },
    {
        id: 11,
        name: "Fabiana Arámbulo",
        subtitle: "Investigación y análisis de datos",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/Fotos%20Lab%20Brenda/Fabiana.jpg",
    },
    {
        id: 12,
        name: "Fabrizio Monge",
        subtitle: "Investigación y análisis de datos",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/Fotos%20Lab%20Brenda/Fabrizio%20UPC.jpg",
    },
    {
        id: 13,
        name: "Sofía Enciso Goicochea",
        subtitle: "Investigación y análisis de datos",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/Fotos%20Lab%20Brenda/Sofia.jpg",
    },
    {
        id: 14,
        name: "Franca Alatrista",
        subtitle: "Investigación y análisis de datos",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/Fotos%20Lab%20Brenda/Franca.jpg",
    },
    {
        id: 15,
        name: "Francisco Calderón",
        subtitle: "Investigación y análisis de datos",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/Fotos%20Lab%20Brenda/Francisco.jpg",
    },
    {
        id: 16,
        name: "William Ramos",
        subtitle: "Desarrollo",
        avatar: "https://media.licdn.com/dms/image/v2/D4E03AQHteEe5AJPWkA/profile-displayphoto-shrink_800_800/B4EZPBAGfrGQAg-/0/1734109850650?e=1740009600&v=beta&t=j40fQThaWrONFxmgqAQ2_6xy7Zf84wUNQeZ5UVn6KzU",
    },
    {
        id: 17,
        name: "Liliana Fu Ye",
        subtitle: "Desarrollo",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/lili.jpg",
    },
    {
        id: 18,
        name: "Carlos Chávez Rojas",
        subtitle: "Desarrollo",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/Carlos%20Chávez.jpeg",
    },
    {
        id: 19,
        name: "Matías Ascasibe",
        subtitle: "Desarrollo",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/Fotos%20Lab%20Brenda/Matias.jpg",
    },
    {
        id: 20,
        name: "Nicoll Araujo",
        subtitle: "Desarrollo",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/Nicoll%20Araujo.jpg",
    },
    {
        id: 21,
        name: "Mayté Ciriaco",
        subtitle: "Supervisión, Coordinación y Edición",
        avatar: "https://media.licdn.com/dms/image/v2/C4E03AQGfkDyzrLyJ9g/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1660609177388?e=1740009600&v=beta&t=ad0OxNkWn-Dw6nC9eM1mcm4fVfimKa4c83azVQWUPIs",
    },
    {
        id: 22,
        name: "Ariana Lira",
        subtitle: "Supervisión, Coordinación y Edición",
        avatar: "https://media.licdn.com/dms/image/v2/C5603AQEXwsbCk3XxjA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1628725096268?e=1740009600&v=beta&t=TGrhPnE7f8TLDUXzENIbikhiKWMbQ0mLBsULIK7lmGs",
    },
    {
        id: 23,
        name: "ESET Perú",
        subtitle: "Agradecimientos Especiales",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/ESET.png",
    },
    {
        id: 24,
        name: "ISACA",
        subtitle: "Agradecimientos Especiales",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/ISACA.jpg",
    },
    {
        id: 25,
        name: "Ebiz",
        subtitle: "Agradecimientos Especiales",
        avatar: "https://lab-ec-upc.github.io/assets/integrantes/EBIZ.jpg",
    },
]